name: 上传模组文件
description: 上传被删除的模组文件
title: "[UPLOAD] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **严格遵循以下步骤** ⚠️
        1. 将 `.jar` 文件**重命名为 `.jar.zip`**  
           (例如: `mod-1.0.jar` → `mod-1.0.jar.zip`)
        2. **直接拖拽**文件到下方评论框  
           (等待上传完成，看到文件链接)
        3. **不要**点击"Attach files"按钮
  - type: textarea
    id: mod-info
    attributes:
      label: 模组信息
      description: |
        请提供:
        - 模组名称
        - Minecraft版本 (如1.20.1)
        - Forge/Fabric版本
    validations:
      required: true
  - type: checkboxes
    id: confirmation
    attributes:
      label: 确认
      options:
        - label: 我确认此文件无版权问题
          required: true
