name: 上传模组文件
description: 上传手中的模组文件
title: "[UPLOAD] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
         **按照以下步骤操作即可** 
        1. 将 `.jar` 文件**重命名为 `.jar.zip`**  
        2. **直接拖拽**文件到下方评论框
        3. **等待上传完成** (看到文件链接)  
        4. 填写字段
  - type: input
    id: mc-version
    attributes:
      label: MC版本
      description: "Minecraft版本 (例如: 1.20.1)"
      placeholder: "1.20.1"
    validations:
      required: true
  - type: dropdown
    id: loader
    attributes:
      label: 模组加载器
      description: "选择模组适用的加载器"
      options:
        - forge
        - neoforge
        - fabric
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: 模组版本
      description: "模组的具体版本 (例如: 10.3.0-beta.5)"
      placeholder: "10.3.0-beta.5"
    validations:
      required: true
  - type: textarea
    id: mod-info
    attributes:
      label: 模组信息
      description: |
        提供额外信息 (可选):
        - 模组来源
        - 测试环境
        - forge版本
        - 功能说明
        - 兼容性注意事项
  - type: checkboxes
    id: confirmation
    attributes:
      label: 确认
      options:
        - label: 我确认此文件无版权问题
          required: true
