name: 上传模组文件
description: 上传被删除的模组文件
title: "[UPLOAD] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **重要提示** ⚠️
        1. 将你的 `.jar` 文件**重命名为 `.jar.zip`** (例如: `expandedstorage-10.3.0-beta.5+1.20.1-forge.jar` → `expandedstorage-10.3.0-beta.5+1.20.1-forge.jar.zip`)
        2. **直接拖拽**重命名后的文件到下方评论框 (等待上传完成)
        3. **不要**点击"Attach files"按钮 (会导致格式错误)
  - type: textarea
    id: description
    attributes:
      label: 模组信息
      description: |
        请提供:
        - 模组名称
        - 适用Minecraft版本
        - Forge/Fabric版本
        - 来源说明 (可选)
    validations:
      required: true
  - type: checkboxes
    id: confirmation
    attributes:
      label: 确认
      options:
        - label: 我确认该文件无版权问题
          required: true
        - label: 我理解文件将永久公开
          required: true
